version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
    payload:
      maxRunTime: 3600
      image: rust:1.21
      command:
        - /bin/bash
        - '-c'
        - >-
           git clone {{event.head.repo.url}} repo &&
           cd repo &&
           git config advice.detachedHead false &&
           git checkout {{event.head.sha}} &&
           cargo test
    metadata:
      name: Tests
      description: 'Run `cargo test`'
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'

